exclude_paths:
- 'docs/'
- 'tests/'
- 'storage/'
- 'src/providers/*.py'
- 'helpers/main/*.js'
- 'helpers/inmanga_com.py'
- 'helpers/unixmanga_nl.sh'
- "LICENSE"
- "README.*"
- "*.yml"
languages:
   Python: true
pep8:
  enabled: true
  checks:
    E501:
      enabled: false
