exclude_paths:
- 'docs/'
- 'tests/'
- 'storage/'
- 'providers/_template.py'
- 'helpers/main/*.js'
- "LICENSE"
- "*.yml"
languages:
   Python: true
pep8:
  enabled: true
  checks:
    E501:
      enabled: false
