exclude_paths:
- 'docs/'
- 'tests/'
- 'storage/'
- 'src/providers/'
- 'src/gui/langs/*.json'
- 'helpers/'
- 'Dockerfile'
- 'LICENSE'
- 'README*'
- '*.yml'
- '*.txt'
- '.scrutinizer.yml'
- '.travis.yml'
- '.codeclimate.yml'
- '.gitignore'
- '.gitmodules'
languages:
   Python: true
pep8:
  enabled: true
  checks:
    E501:
      enabled: false
