checks:
    python:
        code_rating: true
        duplicate_code: true
    javascript: true

build:
    nodes:
        analysis:
            tests:
                before:
                    - 'pip3 install coverage'
                override:
                    -
                        command: 'coverage run tests/pytest.py'
                        coverage:
                            file: '.coverage'
#                            config_file: '.coveragerc'
                            format: 'py-cc'
            environment:
                python:
                    version:
                        - '3.4.6'
                        - '3.5.0'
                        - '3.6.0'
                node:
                    version: 6.0.0


filter:
    excluded_paths:
        - 'docs/'
        - 'tests/'
        - 'storage/'
        - 'providers/_template.py'
        - 'helpers/main/*.js'
        - 'helpers/inmanga_com.py'
        - 'helpers/unixmanga_nl.sh'
        - "LICENSE"
        - "*.yml"
