checks:
  python:
    code_rating: true
    duplicate_code: true
  javascript: true

build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        before:
          - sudo apt remove chromium-browser -y
          - sudo apt update
          - sudo apt install -y dpkg
          - pip3 install coverage
          - pip3 install pyvirtualdisplay
          - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /tmp/chrome.deb
          - sudo dpkg -i /tmp/chrome.deb
          - sudo apt install -y -f --fix-missing
        override:
          -
            command: 'coverage run --omit=manga_py/providers/*.py --source=manga_py pytest.py'
            coverage:
              file: '.coverage'
              format: 'py-cc'
          - py-scrutinizer-run
      environment:
        python: 3.5.3
        node: 6.0.0
filter:
  excluded_paths:
    - manga_py/crypt/sunday_webry_com.py
    - manga_py/crypt/aes.js
    - manga_py/crypt/aes_zp.js
    - tests/*.py
    - pytest.py
    - manga.py
