language: python
python:
- "3.4"
- "3.5"
- "3.6"
install:
- pip install coverage
- pip install codeclimate-test-reporter
- pip install -r requirements.txt
script:
- coverage run tests/pytest.py
after_script:
- codeclimate-test-reporter --file .coverage