env:
  global:
    - CC_TEST_REPORTER_ID=ff7add7a0f454aff7e13c739a06a7aba8e5c8229d3e776e051294341b4721871
addons:
  artifacts: true
language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"
cache: pip
before_install:
  - sudo apt-get -y install nodejs
  - sudo apt-get install python3-setuptools
  - python3 -V
  - chmod +x before_deploy.sh
  - source ./before_deploy.sh
install:
  - npm install -g less less-plugin-clean-css html-minifier
  - pip3 install --upgrade coverage codeclimate-test-reporter setuptools pyinstaller
  - pip3 install -r requirements.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - coverage run --omit=src/providers/*.py --source=src tests/pytest.py
after_script:
  - coverage xml
  - echo "${ALLOW_DEPLOY}"
before_deploy:
  - echo "Start make gh-pages content"
  - cp helpers/.builder.py .
  - cp helpers/.providers_updater.py .
  - cp helpers/manga.spec .
  - python .providers_updater.py
  - lessc helpers/gh_pages_content/style.less helpers/gh_pages_content/style.css
  - html-minifier helpers/gh_pages_content/index.html --output helpers/gh_pages_content/index.html --html5 --remove-comments --remove-tag-whitespace --collapse-inline-tag-whitespace --remove-attribute-quotes --collapse-whitespace
  - html-minifier helpers/gh_pages_content/improvement.html --output helpers/gh_pages_content/improvement.html --html5 --remove-comments --remove-tag-whitespace --collapse-inline-tag-whitespace --remove-attribute-quotes --collapse-whitespace
  - git add -A
  - git commit -a -m upd
deploy:
  - provider: releases
    api_key:
      secure: "BP/yWdetaib7sGB4Xya//3YN+tRio0daBbz1PyTGl7gIDtyBmOScfF7vkREca+LlFJYjih6Sg4sNLbqzfZ0TPHOWxAlYxU+HPw8isBl5josJdjoc+ae31LA0HRbE48kwFnOOePbyv2YBnXa+15I2tDsS+VwTwTX4p9+yoASz/usHcXC8m+M1A/wxAV7GfbWSXP9Ny5pJDDI5wlKO/5euWqgDcAZXHHjEQVfc90dEpBVDkBD3Aft8QYwwP0tqU4IxyngXLm24DQrkNlhFhssBb1LyE4Z3S8EL8oH3vQrSSPLGBZ+8McHlxZioYh1LMTsS9SiOYT2LJlYtBshXaEqG01iSnbrfsysvjYChl/mi+R/P5Lp8iIlu3pSu4W7vXZkGHLySeiYoymR9r2Vz73ogBvnJWi+61K0gqDeN5qZuKwyWzHdFUS3RjIt+wjve7hBeeMmbmLPpXIb49O5Jsj2KEAhHVwgBRkVXHy+StrBRGiCzY576IgFcF/eLO3RR1x9MbBvDONuRd+JZaAJVdHnBqkJNmPsruLKN5SGjSETh96Fpa4zp7S1+MEK6BHex/ldgQjGbbFSdJrYvC84ajQh/DZ12r+2XFSUu0W4dFpDtTm5GngPYLolQbmmoY68f1NAnSJCcrKDTO9bFKIIrOsXzGFlJAIZe6jv+SNtuUjSbELk="
    file_glob: true
    file: dist/manga
    skip_cleanup: true
    on:
      tags: true
      condition: "$allow_deploy == true"
  - provider: pages
    local-dir: helpers/gh_pages_content
    target-branch: gh-pages
    github-token: $MANGADL_TOKEN
    on:
      branch: master
      condition: "$allow_deploy == true"
#    fqdn: yuru-yuri.sttv.me
#see https://docs.travis-ci.com/user/deployment/pages/
allow_failures:
  - python: nightly