version: 1.0.1.{build}
skip_non_tags: true
image: Visual Studio 2015
init:
- ps: git config --global core.autocrlf false
environment:
  pip: C:/Python35/Scripts/pip.exe
  python: C:/Python35/python.exe
install:
- ps: >-
    C:/Python35/Scripts/pip.exe install --disable-pip-version-check --user --upgrade pip setuptools

    C:/Python35/Scripts/pip.exe install cx_Freeze idna

    C:/Python35/Scripts/pip.exe install -r requirements.txt

build: off
test_script:
- cmd: >-
    python appveyor.py build
artifacts:
- path: build
  type: zip
deploy:
- provider: GitHub
  auth_token:
    secure: aqxOwrvNEIZ2ian/bj0ZyfEzMFNWalV5zDfFqpcxfZX47FAIW9ud6kgCU2jm/fMk
  draft: false
  prerelease: false
  force_update: false
  on:
    branch: master
