branches:
  except:
    - test
    - dev

init:
  - git config --global core.autocrlf false # always use unix lineendings

install:
  - cd C:\projects\manga-downloader
  - cp helpers/.builder.py ./
  - cp helpers/.gui.py ./
  - C:/Python35/Scripts/pip.exe install --disable-pip-version-check --user --upgrade pip setuptools
  - C:/Python35/Scripts/pip.exe install coveralls unittest2 nose nose-testconfig mock wheel
  - C:/Python35/Scripts/pip.exe install -r requirements.txt
  - C:/Python35/Scripts/pip.exe install pyinstaller

build: off  # Not a C# project, build stuff at the test step instead.

test_script:
  - cd "C:\Python35\Scripts"
  - dir
  - cd C:\projects\manga-downloader
  - C:/Python35/Scripts/pyinstaller.exe .builder.py --exclude-module PyQT4 --log-level CRITICAL --clean -y -F -n manga.exe

artifacts:
  - path: dist/manga.exe
#  - path: dist/mangaGui.exe

deploy:
  - provider: GitHub
    tag: v0.2.$(appveyor_build_version)
    release: v0.2.$(appveyor_build_version)
    artifact: dist/*.exe
    on:
      branch: master