version: 0.2.{build}
skip_non_tags: true
image: Visual Studio 2015
clone_folder: C:\projects\manga-dl
init:
- ps: git config --global core.autocrlf false
environment:
  PIP: C:/Python35/Scripts/pip.exe
  PYTHON: C:/Python35/python.exe
install:
- ps: >-
    cd C:\projects\manga-dl

    cp helpers/.builder.py ./

    cp helpers/.providers_updater.py ./

    C:/Python35/Scripts/pip.exe install --disable-pip-version-check --user --upgrade pip setuptools

    C:/Python35/Scripts/pip.exe install pyinstaller

    C:/Python35/Scripts/pip.exe install -r requirements.txt

    C:/Python35/python.exe .providers_updater.py

build: off
test_script:
- cmd: >-
    C:/Python35/Scripts/pyinstaller.exe .builder.py --exclude-module PyQt5 --exclude-module PIL.ImageQt --log-level CRITICAL -y -F -n manga.exe
artifacts:
- path: dist/manga.exe
  name: manga.exe
  type: WebDeployPackage
deploy:
- provider: GitHub
  auth_token:
    secure: aqxOwrvNEIZ2ian/bj0ZyfEzMFNWalV5zDfFqpcxfZX47FAIW9ud6kgCU2jm/fMk
  draft: false
  prerelease: false
  force_update: false
  on:
    branch: stable_0.x
